### PR TITLE
feat: remove call to external google font for better load time

### PR DESCRIPTION
**Pull request by OrenMe**
### Description of the Changes

Remove the usage of external google font in order to get better load time.
Currently the request and processing may add up to 0.5s

### CheckLists

- [x] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by dvh91** [comment]
@OrenMe - What's the replacement? This font is used for the default skin.

**Comment by OrenMe** [comment]
@dvh91 no replacement ATM. Do we have another way to bundle font locally with UI?

**Comment by dvh91** [comment]
@OrenMe We can use webfont loader for async load of the font so it won't block rendering.
https://github.com/typekit/webfontloader
Otherwise, I would advice Hillel

**Comment by OrenMe** [comment]
But this will create a possible flash - let's consult with UX/UI and see if we can use default fonts instead.
Addning async font loading library will also defer the purpose of keeping us small as possible

**Pull request merged**
