### PR TITLE
fix(FEC-9555): in mobile devices portrait mode when countdown shows the player jumps to the left

### PR DESCRIPTION
**Pull request by RoyBregman**
### Description of the Changes

commenting out the auto focus
deprecating FEC-9479 for now
solves FEC-9555

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by OrenMe** [comment]
@yairans what are the possible options?
For preventscroll there is a supposed polyfill https://github.com/calvellido/focus-options-polyfill/blob/master/index.js
As previously implemented we can wait for transition to end.
Do you have other solutions?

**Comment by yairans** [comment]
@OrenMe I would check first maybe `preventScroll` indeed supported cross browsers.
also, yesterday @RoyBregman and I saw that it can be fixed by css

**Comment by RoyBregman** [comment]
checking if the browser supports preventScroll doesn't seem to be possible as it is a parameter passed to the focus. There is no pre-check that can be done. Only maybe a post check to see that there was no scrolling.

CSS changes the way we talked about yesterday are also not ideal as they ruin the css effect.

I am working on another approach. will update in the following hour or two

**Comment by OrenMe** [comment]
@RoyBregman see the polyfill I linked, seems it is supported.
Let’s analyze possibilities and choose the one that does the job with least risk.

**Pull request merged**
